export const users = [
  { id: 1, username: 'admin', password: 'admin123', role: 'admin' },
  { id: 2, username: 'cliente', password: 'cliente123', role: 'cliente' },
  { id: 3, username: 'santi', password: 'santi123', role: 'admin' },
  { id: 4, username: 'maria', password: 'maria123', role: 'cliente' },
  { id: 5, username: 'cindy', password: 'cindy123', role: 'admin' },
  { id: 6, username: 'lili', password: 'lili123', role: 'cliente' },
  { id: 7, username: 'gala', password: 'gala123', role: 'cliente' },
  { id: 8, username: 'peter', password: 'peter123', role: 'cliente' }
];

export const products = [
  {
    id: 1,
    name: 'Monstera Deliciosa',
    price: 3500,
    image: '/img/MonsteraDeliciosa.webp', 
    description: 'Una planta tropical con hojas grandes y distintivas. Ideal para interiores luminosos.',
    category: 'interior',
    stock: 10,
    rating: 4.8,
  },
  {
    id: 2,
    name: 'Suculenta Echeveria',
    price: 800,
    image: '/img/SuculentaEcheveria.jpg', 
    description: 'Fácil de cuidar, perfecta para principiantes. Requiere poca agua y mucha luz.',
    category: 'suculenta',
    stock: 25,
    rating: 4.5,
  },
  {
    id: 3,
    name: 'Ficus Lyrata (Violín)',
    price: 4800,
    image: '/img/FicusLyrata.jpeg', 
    description: 'Planta de interior con hojas grandes en forma de violín. Necesita luz indirecta brillante.',
    category: 'interior',
    stock: 5,
    rating: 4.9,
  },
  {
    id: 4,
    name: 'Cactus San Pedro',
    price: 2200,
    image: '/img/CactusSanPedro.jpg', 
    description: 'Un cactus columnar que puede crecer bastante. Resistente y de bajo mantenimiento.',
    category: 'cactus',
    stock: 15,
    rating: 4.2,
  },
  {
    id: 5,
    name: 'Pothos (Epipremnum aureum)',
    price: 1500,
    image: '/img/Pothos.jpg', 
    description: 'Planta colgante muy popular y tolerante. Perfecta para purificar el aire.',
    category: 'interior',
    stock: 20,
    rating: 4.6,
  },
  {
    id: 6,
    name: 'Macetas de Barro (Set x3)',
    price: 1200,
    image: '/img/MacetasdeBarro.jpg', 
    description: 'Set de 3 macetas de barro cocido, ideales para suculentas y plantas pequeñas.',
    category: 'accesorios',
    stock: 30,
    rating: 4.7,
  },
  {
    id: 7,
    name: 'Tierra para Cactus y Suculentas',
    price: 700,
    image: '/img/TierraparaCactusySuculentas.jpg', 
    description: 'Sustrato especial con buen drenaje para cactus y suculentas.',
    category: 'insumos',
    stock: 50,
    rating: 4.9,
  },
  {
    id: 8,
    name: 'Aloe Vera',
    price: 950,
    image: '/img/AloeVera.JPG',
    description: 'Planta con propiedades medicinales y cosméticas. Fácil de cuidar y resistente.',
    category: 'medicinal',
    stock: 18,
    rating: 4.7
  },
  {
    id: 9,
    name: 'Helecho de Boston',
    price: 1800,
    image: '/img/HelechodeBoston.jpg',
    description: 'Planta de interior que prefiere ambientes húmedos. Ideal para colgar.',
    category: 'interior',
    stock: 12,
    rating: 4.3
  },
  {
    id: 10,
    name: 'Orquídea Phalaenopsis',
    price: 6500,
    image: '/img/OrquídeaPhalaenopsis.jpg',
    description: 'Elegante orquídea de flores duraderas. Requiere cuidados específicos.',
    category: 'flor',
    stock: 8,
    rating: 4.9
  },
];